---
new_page_extension: md
auto_deploy: false
admin_path: /static/admin
webhook_url:
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
sections:
  - type: heading
    label: Content
  - type: directory
    path: content/posts
    label: Projects
    create: documents
    match: "**/*"
    new_doc_ext: md
    templates:
    - project
  - type: document
    path: content/data/types.yaml
    label: Project Type List
  - type: document
    path: content/data/info.json
    label: Info Page
  - type: heading
    label: General Config
  - type: document
    path: config.json
    label: Site Info
  - type: document
    path: menu.json
    label: Menu
---